<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="BelastungsermaechtigungProcessService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="urn:com:adcubum:syrius:api:finanzwesen:fakturamgmt:process:belastungsermaechtigung:v0"
                  xmlns:tns="urn:com:adcubum:syrius:api:finanzwesen:fakturamgmt:process:belastungsermaechtigung:v0"
                  xmlns:fi="urn:com:adcubum:syrius:api:finanzwesen:fakturamgmt:process:belastungsermaechtigung:v0:schema"
                  xmlns:flt="urn:com:adcubum:syrius:api:common:faults:v1"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/">
    <wsdl:documentation>Version: 0.0.0</wsdl:documentation>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="urn:com:adcubum:syrius:api:finanzwesen:fakturamgmt:process:belastungsermaechtigung:v0:schema" schemaLocation="schema/BelastungsermaechtigungProcessService.xsd"/>
            <xsd:import namespace="urn:com:adcubum:syrius:api:common:faults:v1" schemaLocation="../../../../../common/faults/v1/faults.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="CreateBelastungsermaechtigungRequestMessage">
        <wsdl:part name="request" element="fi:createBelastungsermaechtigungRequest"/>
    </wsdl:message>
    <wsdl:message name="CreateBelastungsermaechtigungResponseMessage">
        <wsdl:part name="response" element="fi:createBelastungsermaechtigungResponse"/>
    </wsdl:message>
    <wsdl:message name="ApiFaultMessage">
        <wsdl:part name="fault" element="flt:apiFaultInfo"/>
    </wsdl:message>
    
    <wsdl:portType name="BelastungsermaechtigungProcessServicePortType">
        <wsdl:operation name="createBelastungsermaechtigung">
            <wsdl:documentation>Legt die input Daten in einem Belastungsermächtigungsantrag Objekt ab und liefert den technischen Schlüssel des angelegten Objektes zurück.</wsdl:documentation>
            <wsdl:input name="createBelastungsermaechtigungRequest" message="tns:CreateBelastungsermaechtigungRequestMessage"/>
            <wsdl:output name="createBelastungsermaechtigungResponse" message="tns:CreateBelastungsermaechtigungResponseMessage"/>
            <wsdl:fault name="ApiFault" message="tns:ApiFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="BelastungsermaechtigungProcessServiceBinding" type="tns:BelastungsermaechtigungProcessServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="createBelastungsermaechtigung">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="createBelastungsermaechtigungRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="createBelastungsermaechtigungResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ApiFault">
                <soap:fault name="ApiFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="BelastungsermaechtigungProcessService_v0">
        <wsdl:port name="BelastungsermaechtigungProcessService_v0" binding="tns:BelastungsermaechtigungProcessServiceBinding">
            <soap:address location="https://example.com/apibridge-finanzwesen/BelastungsermaechtigungProcessService_v0"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>