<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="UvgKtgEreignismeldungService"
                  targetNamespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:schadenleistungsfallfuehrung:ereignisregistrierung:process:uvgktgereignismeldung:v3"
                  xmlns:tns="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:schadenleistungsfallfuehrung:ereignisregistrierung:process:uvgktgereignismeldung:v3"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:flt="urn:com:adcubum:syrius:api:common:faults:v1"
                  xmlns:pa="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:schadenleistungsfallfuehrung:ereignisregistrierung:process:uvgktgereignismeldung:v3:schema"
                  xmlns:wsdlsi="urn:com:adcubum:syrius:api:common:serviceinfo:v1">

    <wsdl:documentation>Version: 3.1.0</wsdl:documentation>

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import
                    namespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:schadenleistungsfallfuehrung:ereignisregistrierung:process:uvgktgereignismeldung:v3:schema"
                    schemaLocation="schema/UvgKtgEreignismeldungService.xsd"/>
            <xsd:import
                    namespace="urn:com:adcubum:syrius:api:common:faults:v1"
                    schemaLocation="../../../../../../../common/faults/v1/faults.xsd"/>
            <xsd:import
                    namespace="urn:com:adcubum:syrius:api:common:serviceinfo:v1"
                    schemaLocation="../../../../../../../common/serviceinfo/v1/serviceinfo.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="ApiFaultMessage">
        <wsdl:part name="fault" element="flt:apiFaultInfo"/>
    </wsdl:message>

    <wsdl:message name="UvgKtgEreignisDeklarierenRequestMessage">
        <wsdl:part name="request" element="pa:ereignisDeklarierenRequest"/>
    </wsdl:message>

    <wsdl:message name="UvgKtgEreignisDeklarierenResponseMessage">
        <wsdl:part name="response" element="pa:ereignisDeklarierenResponse"/>
    </wsdl:message>

    <wsdl:portType name="UvgKtgEreignismeldungServicePortType">
        <wsdl:operation name="ereignisDeklarieren">
            <wsdl:documentation>Deklariert ein Ereignis gemäss UVG/KTG und liefert die reservierte Schadennummer zurück.
            </wsdl:documentation>
            <wsdl:input name="ereignisDeklarierenRequest" message="tns:UvgKtgEreignisDeklarierenRequestMessage"/>
            <wsdl:output name="ereignisDeklarierenResponse"
                         message="tns:UvgKtgEreignisDeklarierenResponseMessage"/>
            <wsdl:fault name="ApiFault" message="tns:ApiFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="UvgKtgEreignismeldungServiceBinding" type="tns:UvgKtgEreignismeldungServicePortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ereignisDeklarieren">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="ereignisDeklarierenRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ereignisDeklarierenResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ApiFault">
                <soap:fault name="ApiFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="UvgKtgEreignismeldungService_v3">
        <wsdl:documentation>
            Deklariert ein Ereignis gemäss UVG/KTG und liefert die reservierte Schadennummer zurück.
        </wsdl:documentation>

        <wsdlsi:serviceInfo>
            <wsdlsi:deprecation>
                <wsdlsi:deprecationReason>Replaced</wsdlsi:deprecationReason>
                <wsdlsi:replacedBy>
                    <wsdlsi:serviceName>EreignismeldungService_v1</wsdlsi:serviceName>
                    <wsdlsi:targetNamespace>
                        urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:meldung:ereignismeldung:process:v1
                    </wsdlsi:targetNamespace>
                </wsdlsi:replacedBy>
                <wsdlsi:ticketReference>ASLM-425</wsdlsi:ticketReference>
            </wsdlsi:deprecation>
        </wsdlsi:serviceInfo>

        <wsdl:port name="UvgKtgEreignismeldungService_v3" binding="tns:UvgKtgEreignismeldungServiceBinding">
            <soap:address
                    location="https://example.com/apibridge-schadenleistungsmgmt/UvgKtgEreignismeldungService_v3"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
