<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="UvgKtgNachrichtenService"
                  targetNamespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:nachrichten:process:v1"
                  xmlns:tns="urn:com:adcubum:syrius:api:schadenleistungsmgmt:nachrichten:process:v1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:flt="urn:com:adcubum:syrius:api:common:faults:v1"
                  xmlns:pa="urn:com:adcubum:syrius:api:schadenleistungsmgmt:nachrichten:process:v1:schema">

    <wsdl:documentation>Version: 1.0.0</wsdl:documentation>

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import
                    namespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:nachrichten:process:v1:schema"
                    schemaLocation="schema/UvgKtgNachrichtenService.xsd"/>
            <xsd:import
                    namespace="urn:com:adcubum:syrius:api:common:faults:v1"
                    schemaLocation="../../../../common/faults/v1/faults.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="ApiFaultMessage">
        <wsdl:part name="fault" element="flt:apiFaultInfo"/>
    </wsdl:message>

    <wsdl:message name="UvgKtgNachrichtenRequestMessage">
        <wsdl:part name="request" element="pa:nachrichtEmpfangenRequest"/>
    </wsdl:message>

    <wsdl:message name="UvgKtgNachrichtenResponseMessage">
        <wsdl:part name="response" element="pa:nachrichtEmpfangenResponse"/>
    </wsdl:message>

    <wsdl:portType name="UvgKtgNachrichtenServicePortType">
        <wsdl:operation name="nachrichtEmpfangen">
            <wsdl:documentation>Empfängt eine Nachricht</wsdl:documentation>
            <wsdl:input name="nachrichtEmpfangenRequest" message="tns:UvgKtgNachrichtenRequestMessage"/>
            <wsdl:output name="nachrichtEmpfangenResponse" message="tns:UvgKtgNachrichtenResponseMessage"/>
            <wsdl:fault name="ApiFault" message="tns:ApiFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="UvgKtgNachrichtenServiceBinding" type="tns:UvgKtgNachrichtenServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="nachrichtEmpfangen">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="nachrichtEmpfangenRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="nachrichtEmpfangenResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ApiFault">
                <soap:fault name="ApiFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="UvgKtgNachrichtenService_v1">
        <wsdl:documentation>Empfängt eine Nachricht</wsdl:documentation>
        <wsdl:port name="UvgKtgNachrichtenService_v1" binding="tns:UvgKtgNachrichtenServiceBinding">
            <soap:address location="https://example.com/apibridge-schadenleistungsmgmt/UvgKtgNachrichtenService_v1"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
