<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="KVUVMeldungService"
				  targetNamespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:meldung:v1"
				  xmlns:tns="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:meldung:v1"
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
				  xmlns:flt="urn:com:adcubum:syrius:api:common:faults:v1"
				  xmlns:pa="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:meldung:v1:schema">

	<wsdl:documentation>Version: 1.0.0</wsdl:documentation>

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import
					namespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:meldung:v1:schema"
					schemaLocation="schema/KVUVMeldungService.xsd"/>
			<xsd:import
					namespace="urn:com:adcubum:syrius:api:common:faults:v1"
					schemaLocation="../../../../common/faults/v1/faults.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="ApiFaultMessage">
		<wsdl:part name="fault" element="flt:apiFaultInfo"/>
	</wsdl:message>

	<wsdl:message name="KVUVMeldungRequestMessage">
		<wsdl:part name="request" element="pa:empfangeKVUVMeldungRequest" />
	</wsdl:message>

	<wsdl:message name="KVUVMeldungResponseMessage">
		<wsdl:part name="response" element="pa:empfangeKVUVMeldungResponse" />
	</wsdl:message>

	<wsdl:portType name="KVUVMeldungServicePortType">
		<wsdl:operation name="empfangeKVUVMeldung">
			<wsdl:documentation>Empfangt eine KVUVMeldung
			</wsdl:documentation>
			<wsdl:input name="empfangeKVUVMeldungRequest" message="tns:KVUVMeldungRequestMessage" />
			<wsdl:output name="empfangeKVUVMeldungResponse"	message="tns:KVUVMeldungResponseMessage" />
			<wsdl:fault name="ApiFault" message="tns:ApiFaultMessage" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="KVUVMeldungServiceBinding" type="tns:KVUVMeldungServicePortType">
		<soap:binding style="document"
					  transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="empfangeKVUVMeldung">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input name="empfangeKVUVMeldungRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="empfangeKVUVMeldungResponse">
				<soap:body use="literal"/>
			</wsdl:output>
			<wsdl:fault name="ApiFault">
				<soap:fault name="ApiFault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="KVUVMeldungService_v1">
		<wsdl:documentation>
		Empfaengt eine KVUV Meldung
		</wsdl:documentation>
		<wsdl:port name="KVUVMeldungService_v1" binding="tns:KVUVMeldungServiceBinding">
			<soap:address
					location="https://example.com/apibridge-schadenleistungsmgmt/KVUVMeldungService_v1"/>
		</wsdl:port>

	</wsdl:service>

</wsdl:definitions>
