<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="EreignismeldungService"
                  targetNamespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:meldung:ereignismeldung:process:v1"
                  xmlns:tns="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:meldung:ereignismeldung:process:v1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:flt="urn:com:adcubum:syrius:api:common:faults:v1"
                  xmlns:pa="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:meldung:ereignismeldung:process:v1:schema">

    <wsdl:documentation>Version: 1.4.0</wsdl:documentation>

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import
                    namespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:meldung:ereignismeldung:process:v1:schema"
                    schemaLocation="schema/EreignismeldungService.xsd"/>
            <xsd:import
                    namespace="urn:com:adcubum:syrius:api:common:faults:v1"
                    schemaLocation="../../../../../../../../../../com/adcubum/syrius/api/common/faults/v1/faults.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="ApiFaultMessage">
        <wsdl:part name="fault" element="flt:apiFaultInfo"/>
    </wsdl:message>

    <wsdl:message name="EreignismeldungDeklarierenRequestMessage">
        <wsdl:part name="request" element="pa:ereignismeldungDeklarierenRequest"/>
    </wsdl:message>

    <wsdl:message name="EreignismeldungDeklarierenResponseMessage">
        <wsdl:part name="response" element="pa:ereignismeldungDeklarierenResponse"/>
    </wsdl:message>

    <wsdl:portType name="EreignismeldungServicePortType">
        <wsdl:operation name="ereignismeldungDeklarieren">
            <wsdl:documentation>Deklariert ein Ereignis gemäss UVG/KVG und liefert die reservierte Schadennummer zurück.
            </wsdl:documentation>
            <wsdl:input name="ereignismeldungDeklarierenRequest"
                        message="tns:EreignismeldungDeklarierenRequestMessage"/>
            <wsdl:output name="ereignismeldungDeklarierenResponse"
                         message="tns:EreignismeldungDeklarierenResponseMessage"/>
            <wsdl:fault name="ApiFault" message="tns:ApiFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="EreignismeldungServiceBinding" type="tns:EreignismeldungServicePortType">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="ereignismeldungDeklarieren">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="ereignismeldungDeklarierenRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="ereignismeldungDeklarierenResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ApiFault">
                <soap:fault name="ApiFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="EreignismeldungService_v1">
        <wsdl:documentation>
            Deklariert ein Ereignis gemäss UVG/KVG und liefert die reservierte Schadennummer zurück.
        </wsdl:documentation>
        <wsdl:port name="EreignismeldungService_v1" binding="tns:EreignismeldungServiceBinding">
            <soap:address
                    location="https://example.com/apibridge-schadenleistungsmgmt/EreignismeldungService_v1"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
