<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="ArbeitsunfaehigkeitsverlaufMeldungsService"
                  targetNamespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:schadenleistungsfallfuehrung:arbeitsunfaehigkeitsmeldung:process:v1"
                  xmlns:tns="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:schadenleistungsfallfuehrung:arbeitsunfaehigkeitsmeldung:process:v1"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:flt="urn:com:adcubum:syrius:api:common:faults:v1"
                  xmlns:auf="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:schadenleistungsfallfuehrung:arbeitsunfaehigkeitsmeldung:process:v1:schema">
    <wsdl:documentation>Version: 1.0.0</wsdl:documentation>

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="urn:com:adcubum:syrius:api:common:faults:v1"
                        schemaLocation="../../../../../../common/faults/v1/faults.xsd"/>
            <xsd:import
                    namespace="urn:com:adcubum:syrius:api:schadenleistungsmgmt:kvuv:schadenleistungsfallfuehrung:arbeitsunfaehigkeitsmeldung:process:v1:schema"
                    schemaLocation="schema/ArbeitsunfaehigkeitsverlaufMeldungsService.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="CreateArbeitsunfaehigkeitsverlaufMeldungsRequestMessage">
        <wsdl:part name="Request" element="auf:createArbeitsunfaehigkeitsverlaufRequest"/>
    </wsdl:message>

    <wsdl:message name="CreateArbeitsunfaehigkeitsverlaufMeldungsResponseMessage">
        <wsdl:part name="Response" element="auf:createArbeitsunfaehigkeitsverlaufResponse"/>
    </wsdl:message>

    <wsdl:message name="ApiFaultMessage">
        <wsdl:part name="fault" element="flt:apiFaultInfo"/>
    </wsdl:message>

    <wsdl:portType name="ArbeitsunfaehigkeitsverlaufMeldungsServicePortType">
        <wsdl:operation name="createArbeitsunfaehigkeitsverlaufMeldung">
            <wsdl:documentation>Meldet eine Arbeitsunfähigkeit.
            </wsdl:documentation>
            <wsdl:input name="createArbeitsunfaehigkeitsverlaufMeldungRequest" message="tns:CreateArbeitsunfaehigkeitsverlaufMeldungsRequestMessage"/>
            <wsdl:output name="createArbeitsunfaehigkeitsverlaufMeldungResponse"
                         message="tns:CreateArbeitsunfaehigkeitsverlaufMeldungsResponseMessage"/>
            <wsdl:fault name="ApiFault" message="tns:ApiFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="ArbeitsunfaehigkeitsverlaufMeldungsServiceBinding" type="tns:ArbeitsunfaehigkeitsverlaufMeldungsServicePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="createArbeitsunfaehigkeitsverlaufMeldung">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="createArbeitsunfaehigkeitsverlaufMeldungRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="createArbeitsunfaehigkeitsverlaufMeldungResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ApiFault">
                <soap:fault name="ApiFault" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="ArbeitsunfaehigkeitsverlaufMeldungsService_v1">
        <wsdl:documentation>
            Ein schreibender Service für die Meldung eines Arbeitsunfaehigkeitsverlaufs.
        </wsdl:documentation>
        <wsdl:port name="ArbeitsunfaehigkeitsverlaufMeldungsService_v1" binding="tns:ArbeitsunfaehigkeitsverlaufMeldungsServiceBinding">
            <soap:address location="http://example.com/apibridge-schadenleistungsmgmt/ArbeitsunfaehigkeitsverlaufMeldungsService_v1"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
